org: guillevalin
app: cotalker-hello-world
service: cotalker-hello-world

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  sendMessage:
    handler: app/handler.sendMessage
    events:
      - http:
          path: sendmessage
          method: post
